### ISSUE TITLE
typo in 4626

### ISSUE THREAD

**Issue by thedavidmeister** [ethereum/EIPs#5084]
```
 deposit
Mints shares Vault shares to receiver by depositing exactly `amount` of underlying tokens.
```

```
  inputs:
    - name: assets
      type: uint256
    - name: receiver
      type: address
```

inputs should be `amount` rather than `assets`?
